# Generated by Django 4.1.2 on 2022-10-14 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_myuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
